spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///online_shopping?useSSL=false&characterEncoding=utf-8&useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
server:
  port: 8082
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false